import { toCsv, type ExportFile } from "./exporters.ts";
import type { CompletedGameRecord, ExperimentRecord, ExperimentSettings } from "./experiments.ts";

export const ANALYZER_VERSION = "phase2-rules-v1";
export const ANALYSIS_RULE_CONFIG = {
  openingWinRate: { minGames: 10, watch: 0.8, suspicious: 0.9, high: 0.95, highMinGames: 20 },
  firstPlayerAdvantage: { minGames: 30, watchGap: 0.25, suspiciousGap: 0.4, highGap: 0.55 },
  mirrorAsymmetry: { minGamesEach: 5, watchGap: 0.3, suspiciousMinGamesEach: 10, suspiciousGap: 0.5 },
  dominantBlueReply: { minOpenings: 5, minGames: 10, blueWinRate: 0.75, autoShare: 0.7 },
  depthInstability: { minGamesEach: 5, resultGap: 0.3 },
  drawPathology: { minGames: 10, watchRate: 0.2, highRate: 0.4 },
  longGame: { minGames: 5, medianMultiplier: 1.5 },
  lowDiversity: { minGames: 10, uniqueFirst10Share: 0.2, dominantCompleteLineShare: 0.5 },
  insufficientSample: { openingGames: 5 },
} as const;

export type FlagPriority = "normal" | "watch" | "suspicious" | "high priority";
export type ConfidenceLevel = "very low" | "low" | "moderate" | "high";
export type FlagCategory = "opening-win-rate" | "first-player-advantage" | "mirror-asymmetry" | "dominant-blue-reply" | "depth-instability" | "draw-pathology" | "repetition-pathology" | "no-progress-pathology" | "max-plies-pathology" | "unusually-long-games" | "low-line-diversity" | "tactical-anomaly" | "replay-failure" | "illegal-move" | "insufficient-sample" | "result-concentration";
export interface Summary { games: number; greenWins: number; blueWins: number; draws: number; greenWinRate: number; blueWinRate: number; drawRate: number; averagePlies: number; medianPlies: number; }
export interface OpeningResult extends Summary { opening: string; shortestGame: number; longestGame: number; uniqueCompleteMoveSequences: number; uniqueFirst10PlySequences: number; actualBlueFirstMoveDistribution: Record<string, number>; forcedBlueReplyDistribution: Record<string, number>; repetitionDraws: number; noProgressDraws: number; maxPliesDraws: number; tacticalEvents: Record<string, number>; representativeGameIds: string[]; }
export interface BlueReplyResult extends Summary { reply: string; openingsFaced: string[]; frequencySelected: number; resultByOpening: Record<string, Summary>; }
export interface MirrorResult { opening: string; mirroredOpening: string; sampleSize: number; mirroredSampleSize: number; winRateDifference: number; drawRateDifference: number; averagePliesDifference: number; blueReplyDistributionDifference: number; adequatelySampled: boolean; priority: FlagPriority; representativeGameIds: string[]; }
export interface AnalysisFlag { flagId: string; analysisId: string; experimentId: string; category: FlagCategory; priority: FlagPriority; title: string; explanation: string; evidence: Record<string, unknown>; sampleSize: number; confidenceLevel: ConfidenceLevel; affectedOpenings: string[]; affectedReplies: string[]; representativeGameIds: string[]; recommendedAction: string; proposedFollowUpId?: string; dismissed: boolean; createdAt: string; }
export interface FollowUpProposal { proposalId: string; analysisId: string; experimentId: string; sourceFlagId: string; title: string; rationale: string; estimatedTotalGames: number; expectedRuntimeWarning: string; inheritedSettings: ExperimentSettings; changedFields: Record<string, unknown>; proposedSettings: ExperimentSettings; createdAt: string; }
export interface ExperimentAnalysis { analysisId: string; experimentId: string; createdAt: string; updatedAt: string; analyzerVersion: string; status: "preliminary" | "final"; gameCount: number; openingCount: number; settingsSummary: Record<string, unknown>; overallResults: Summary & { shortestGame: number; longestGame: number; replayFailures: number; illegalMoves: number; repetitionDraws: number; noProgressDraws: number; maxPliesDraws: number }; openingResults: OpeningResult[]; blueReplyResults: BlueReplyResult[]; forcedBlueReplyResults: BlueReplyResult[]; mirrorResults: MirrorResult[]; drawAnalysis: Record<string, number>; lengthAnalysis: Record<string, number>; diversityAnalysis: Record<string, number>; tacticalEventAnalysis: Record<string, number>; crossExperimentComparisons: CrossExperimentComparison[]; replayWorthyGames: Array<{ gameId: string; reason: string }>; flagCount: number; highestPriority: FlagPriority; stale: boolean; sourceExperimentUpdatedAt: string; }
export interface CrossExperimentComparison { experimentId: string; comparedExperimentId: string; compatible: boolean; confidenceLevel: ConfidenceLevel; warning?: string; depthDelta?: number; openingLevelChanges: Array<{ opening: string; rateDifference: number; winnerReversed: boolean }>; flags: AnalysisFlag[]; }

const cols: Record<string, string> = { A:"M",B:"L",C:"K",D:"J",E:"I",F:"H",G:"G",H:"F",I:"E",J:"D",K:"C",L:"B",M:"A" };
export function mirrorCoordinate(coord: string): string | null { const m = /^([A-M])(\d{1,2})$/i.exec(coord.trim()); return m ? `${cols[m[1].toUpperCase()]}${m[2]}` : null; }
export function mirrorMoveLabel(label: string): string | null { let ok = false; const out = label.replace(/\b([A-M]\d{1,2})\b/gi, (c) => { const mirrored = mirrorCoordinate(c); ok ||= !!mirrored && mirrored !== c.toUpperCase(); return mirrored ?? c; }); return /\b[A-M]\d{1,2}\b/i.test(label) ? out : null; }
export const canonicalMirrorLabel = (label: string) => { const m = mirrorMoveLabel(label); return m && m < label ? m : label; };

export function analyzeExperiment(exp: ExperimentRecord, games: CompletedGameRecord[], priorFlags: AnalysisFlag[] = [], comparisons: Array<{ experiment: ExperimentRecord; games: CompletedGameRecord[] }> = []): { analysis: ExperimentAnalysis; flags: AnalysisFlag[]; proposals: FollowUpProposal[] } {
  const createdAt = new Date().toISOString(); const analysisId = `analysis-${exp.experimentId}-${Date.now().toString(36)}`;
  const overall = overallSummary(games); const openings = [...group(games, g => g.opening ?? "(unknown)").entries()].map(([opening, rows]) => openingSummary(opening, rows));
  const blueReplies = [...group(games.filter(g=>g.actualBlueFirstMove), g => g.actualBlueFirstMove ?? "(none)").entries()].map(([reply, rows]) => replySummary(reply, rows, games.length));
  const forcedReplies = [...group(games.filter(g=>g.forcedBlueReply), g => g.forcedBlueReply ?? "(none)").entries()].map(([reply, rows]) => replySummary(reply, rows, games.length));
  const mirrors = mirrorResults(openings); const tactical = sumMetrics(games); const flags: AnalysisFlag[] = [];
  const add = (f: Omit<AnalysisFlag,"flagId"|"analysisId"|"experimentId"|"dismissed"|"createdAt">) => { const old = priorFlags.find(p=>p.category===f.category && p.title===f.title); flags.push({ ...f, flagId: old?.flagId ?? `flag-${flags.length+1}-${Date.now().toString(36)}`, analysisId, experimentId: exp.experimentId, dismissed: old?.dismissed ?? false, createdAt }); };
  for (const o of openings) {
    if (o.games < ANALYSIS_RULE_CONFIG.insufficientSample.openingGames) add(flag("insufficient-sample","watch",`Insufficient sample for ${o.opening}`,`Only ${o.games} games exist for this opening; this is a note, not an exploit signal.`,{opening:o.opening,games:o.games},o.games,"very low",[o.opening],[],o.representativeGameIds,"Run more seeds before interpreting this opening."));
    const top = Math.max(o.greenWinRate,o.blueWinRate); if (o.games >= 10 && top >= .8) add(flag("opening-win-rate", top >= .95 && o.games >= 20 ? "high priority" : top >= .9 ? "suspicious" : "watch",`${top===o.greenWinRate?"Green":"Blue"} concentrated wins for ${o.opening}`,`${pct(top)} of ${o.games} games were won by one side. Flags are triage only, not proof.`,{greenWinRate:o.greenWinRate,blueWinRate:o.blueWinRate},o.games,confidence(o.games),[o.opening],[],o.representativeGameIds,"Repeat this opening and its mirror with additional seeds."));
    if (o.games >= 5 && overall.medianPlies && o.medianPlies >= overall.medianPlies*1.5) add(flag("unusually-long-games","watch",`Long games for ${o.opening}`,`Median plies are at least 50% above the experiment median.`,{medianPlies:o.medianPlies,experimentMedian:overall.medianPlies},o.games,confidence(o.games),[o.opening],[],o.representativeGameIds,"Replay representative long games and rerun if needed."));
    const uniqueShare = o.uniqueFirst10PlySequences/Math.max(1,o.games); const dominant = maxCount(group(games.filter(g=> (g.opening??"(unknown)")===o.opening), g=>g.moves.join(" ")))/Math.max(1,o.games); if (o.games>=10 && (uniqueShare<.2 || dominant>.5)) add(flag("low-line-diversity","watch",`Low line diversity for ${o.opening}`,`The same early or complete lines recur unusually often.`,{uniqueFirst10Share:uniqueShare,dominantCompleteLineShare:dominant},o.games,confidence(o.games),[o.opening],[],o.representativeGameIds,"Run diverse-agent or forced-reply follow-up games."));
  }
  if (games.length>=30 && overall.greenWinRate-overall.blueWinRate>=.25) add(flag("first-player-advantage", overall.greenWinRate-overall.blueWinRate>=.55?"high priority":overall.greenWinRate-overall.blueWinRate>=.4?"suspicious":"watch", "Overall first-player advantage", "Green won materially more often than Blue across this experiment.", {greenWinRate:overall.greenWinRate,blueWinRate:overall.blueWinRate,gap:overall.greenWinRate-overall.blueWinRate}, games.length, confidence(games.length), [], [], games.slice(0,5).map(g=>g.gameId), "Repeat with mirrored openings and comparable seeds."));
  for (const m of mirrors.filter(m=>m.adequatelySampled && m.winRateDifference>=.3)) add(flag("mirror-asymmetry", m.winRateDifference>=.5&&m.sampleSize>=10&&m.mirroredSampleSize>=10?"suspicious":"watch", `Mirror asymmetry: ${m.opening} vs ${m.mirroredOpening}`, "Mirrored openings produced materially different result rates.", m as any, m.sampleSize+m.mirroredSampleSize, confidence(m.sampleSize+m.mirroredSampleSize,true), [m.opening,m.mirroredOpening], [], m.representativeGameIds, "Run equal-seed mirrored follow-up games."));
  for (const r of blueReplies) { if (r.games>=10 && r.openingsFaced.length>=5 && r.blueWinRate>=.75) add(flag("dominant-blue-reply","suspicious",`Dominant Blue reply ${r.reply}`,`This Blue first move beat Green in ${pct(r.blueWinRate)} of games across ${r.openingsFaced.length} openings.`,{blueWinRate:r.blueWinRate,openingsFaced:r.openingsFaced},r.games,confidence(r.games),r.openingsFaced,[r.reply],[],"Force this reply and its mirror in a follow-up.")); if (r.frequencySelected>=.7) add(flag("result-concentration","watch",`Blue reply selected very often: ${r.reply}`,`This reply appears in ${pct(r.frequencySelected)} of automatic-response games.`,{frequencySelected:r.frequencySelected},r.games,confidence(r.games),r.openingsFaced,[r.reply],[],"Test whether automatic response diversity is too low.")); }
  for (const [cat,key] of [["repetition-pathology","repetitionDraws"],["no-progress-pathology","noProgressDraws"],["max-plies-pathology","maxPliesDraws"]] as const) { const n=(overall as any)[key]; const rate=n/Math.max(1,games.length); if(games.length>=10&&rate>=.2) add(flag(cat,rate>=.4?"high priority":"watch",`${key} draw pathology`,`The ${key} rate exceeded the configured threshold.`,{count:n,rate},games.length,confidence(games.length),[],[],games.filter(g=>drawKind(g,key)).slice(0,5).map(g=>g.gameId),"Replay representative draws and rerun with targeted settings.")); }
  const replayBad=games.filter(g=>!g.finalReplayOk||!g.replayOk); if(replayBad.length) add(flag("replay-failure","high priority","Replay verification failures","At least one persisted game failed replay verification.",{count:replayBad.length},replayBad.length,"very low",[],[],replayBad.map(g=>g.gameId),"Inspect raw game records before strategic interpretation."));
  const illegal=games.filter(g=>g.metrics?.illegalMoves); if(illegal.length) add(flag("illegal-move","high priority","Illegal move diagnostics","At least one game exported illegal move diagnostics.",{count:illegal.length},illegal.length,"very low",[],[],illegal.map(g=>g.gameId),"Fix data quality before strategic interpretation."));
  const cross = comparisons.map(c=>compareExperiments(exp,games,c.experiment,c.games,analysisId)); for (const c of cross) flags.push(...c.flags);
  const proposals = flags.filter(f=>f.category!=="insufficient-sample").map(f=>proposalForFlag(exp, analysisId, f)); flags.forEach(f=>f.proposedFollowUpId = proposals.find(p=>p.sourceFlagId===f.flagId)?.proposalId);
  const analysis: ExperimentAnalysis = { analysisId, experimentId: exp.experimentId, createdAt, updatedAt: createdAt, analyzerVersion: ANALYZER_VERSION, status: exp.status === "completed" ? "final" : "preliminary", gameCount: games.length, openingCount: openings.length, settingsSummary: settingsSummary(exp.settings), overallResults: overall, openingResults: openings, blueReplyResults: blueReplies, forcedBlueReplyResults: forcedReplies, mirrorResults: mirrors, drawAnalysis: { repetitionDraws: overall.repetitionDraws, noProgressDraws: overall.noProgressDraws, maxPliesDraws: overall.maxPliesDraws }, lengthAnalysis: { averagePlies: overall.averagePlies, medianPlies: overall.medianPlies, shortestGame: overall.shortestGame, longestGame: overall.longestGame }, diversityAnalysis: { uniqueFirst10: new Set(games.map(g=>g.first10)).size, uniqueCompleteLines: new Set(games.map(g=>g.moves.join(" "))).size }, tacticalEventAnalysis: tactical, crossExperimentComparisons: cross, replayWorthyGames: replayWorthy(games), flagCount: flags.length, highestPriority: highest(flags), stale: false, sourceExperimentUpdatedAt: exp.updatedAt };
  return { analysis, flags, proposals };
}

function flag(category:FlagCategory,priority:FlagPriority,title:string,explanation:string,evidence:Record<string,unknown>,sampleSize:number,confidenceLevel:ConfidenceLevel,affectedOpenings:string[],affectedReplies:string[],representativeGameIds:string[],recommendedAction:string){return{category,priority,title,explanation,evidence,sampleSize,confidenceLevel,affectedOpenings,affectedReplies,representativeGameIds,recommendedAction};}
function summary(rows: CompletedGameRecord[]): Summary { const pl=rows.map(g=>g.plies).sort((a,b)=>a-b); const gw=rows.filter(g=>g.winner==="green").length,bw=rows.filter(g=>g.winner==="blue").length,d=rows.length-gw-bw; return {games:rows.length,greenWins:gw,blueWins:bw,draws:d,greenWinRate:gw/Math.max(1,rows.length),blueWinRate:bw/Math.max(1,rows.length),drawRate:d/Math.max(1,rows.length),averagePlies:round(pl.reduce((a,b)=>a+b,0)/Math.max(1,pl.length)),medianPlies:pl.length?pl[Math.floor((pl.length-1)/2)]:0};}
function overallSummary(rows: CompletedGameRecord[]): ExperimentAnalysis["overallResults"] { const s=summary(rows); return {...s,shortestGame:Math.min(...rows.map(g=>g.plies),0),longestGame:Math.max(...rows.map(g=>g.plies),0),replayFailures:rows.filter(g=>!g.finalReplayOk||!g.replayOk).length,illegalMoves:rows.reduce((n,g)=>n+(g.metrics?.illegalMoves??0),0),repetitionDraws:rows.filter(g=>g.repetitionDiagnostics?.repetitionDraw||g.drawReason==="threefold-repetition").length,noProgressDraws:rows.filter(g=>g.repetitionDiagnostics?.noProgressDraw||g.drawReason==="no-progress").length,maxPliesDraws:rows.filter(g=>g.drawReason==="max-plies"||g.drawReason==="maxPlies").length};}
function openingSummary(opening:string,rows:CompletedGameRecord[]):OpeningResult{const s=summary(rows);return{...s,opening,shortestGame:Math.min(...rows.map(g=>g.plies)),longestGame:Math.max(...rows.map(g=>g.plies)),uniqueCompleteMoveSequences:new Set(rows.map(g=>g.moves.join(" "))).size,uniqueFirst10PlySequences:new Set(rows.map(g=>g.first10)).size,actualBlueFirstMoveDistribution:counts(rows.map(g=>g.actualBlueFirstMove??"(none)")),forcedBlueReplyDistribution:counts(rows.map(g=>g.forcedBlueReply??"(none)")),repetitionDraws:rows.filter(g=>g.repetitionDiagnostics?.repetitionDraw).length,noProgressDraws:rows.filter(g=>g.repetitionDiagnostics?.noProgressDraw).length,maxPliesDraws:rows.filter(g=>g.drawReason==="max-plies"||g.drawReason==="maxPlies").length,tacticalEvents:sumMetrics(rows),representativeGameIds:rows.slice(0,5).map(g=>g.gameId)};}
function replySummary(reply:string,rows:CompletedGameRecord[],total:number):BlueReplyResult{const s=summary(rows);const by=group(rows,g=>g.opening??"(unknown)");return{...s,reply,openingsFaced:[...by.keys()],frequencySelected:rows.length/Math.max(1,total),resultByOpening:Object.fromEntries([...by.entries()].map(([k,v])=>[k,summary(v)]))};}
function mirrorResults(openings:OpeningResult[]):MirrorResult[]{const by=new Map(openings.map(o=>[o.opening,o]));const byKey=new Map(openings.map(o=>[coordKey(o.opening),o]));const seen=new Set<string>();const out:MirrorResult[]=[];for(const o of openings){const mlabel=mirrorMoveLabel(o.opening);const mkey=mlabel?coordKey(mlabel):null; if(!mlabel||seen.has(o.opening))continue; const m=by.get(mlabel)??(mkey?byKey.get(mkey):undefined); if(!m||m.opening===o.opening)continue;seen.add(o.opening);seen.add(m.opening);const diff=dist(o.actualBlueFirstMoveDistribution,m.actualBlueFirstMoveDistribution);out.push({opening:o.opening,mirroredOpening:m.opening,sampleSize:o.games,mirroredSampleSize:m.games,winRateDifference:round(Math.abs(o.greenWinRate-m.greenWinRate)),drawRateDifference:round(Math.abs(o.drawRate-m.drawRate)),averagePliesDifference:round(Math.abs(o.averagePlies-m.averagePlies)),blueReplyDistributionDifference:diff,adequatelySampled:o.games>=5&&m.games>=5,priority:Math.abs(o.greenWinRate-m.greenWinRate)>=.5?"suspicious":Math.abs(o.greenWinRate-m.greenWinRate)>=.3?"watch":"normal",representativeGameIds:[...o.representativeGameIds,...m.representativeGameIds].slice(0,6)});}return out;}
export function compareExperiments(a:ExperimentRecord,aGames:CompletedGameRecord[],b:ExperimentRecord,bGames:CompletedGameRecord[],analysisId="comparison"):CrossExperimentComparison{const compatible=isCompatible(a,b);const ao=[...group(aGames,g=>g.opening??"(unknown)").entries()].map(([k,v])=>openingSummary(k,v));const bo=new Map([...group(bGames,g=>g.opening??"(unknown)").entries()].map(([k,v])=>[k,openingSummary(k,v)]));const changes=ao.filter(o=>bo.has(o.opening)).map(o=>{const other=bo.get(o.opening)!;return{opening:o.opening,rateDifference:round(Math.abs(o.greenWinRate-other.greenWinRate)),winnerReversed:(o.greenWins>o.blueWins)!==(other.greenWins>other.blueWins)}});const flags:AnalysisFlag[]=changes.filter(c=>c.rateDifference>=.3||c.winnerReversed).map((c,i)=>({flagId:`depth-${i}-${Date.now().toString(36)}`,analysisId,experimentId:a.experimentId,category:"depth-instability",priority:c.winnerReversed?"suspicious":"watch",title:`Depth instability for ${c.opening}`,explanation:"Compatible experiments differed mainly by search depth and produced a large result change or winner reversal.",evidence:c,sampleSize:(ao.find(o=>o.opening===c.opening)?.games??0)+(bo.get(c.opening)?.games??0),confidenceLevel:compatible?"moderate":"low",affectedOpenings:[c.opening],affectedReplies:[],representativeGameIds:[],recommendedAction:"Rerun the opening at both depths with matched seeds.",dismissed:false,createdAt:new Date().toISOString()}));return{experimentId:a.experimentId,comparedExperimentId:b.experimentId,compatible,confidenceLevel:compatible?"moderate":"low",warning:compatible?undefined:"Experiments differ in more than search depth or seed range; compare cautiously.",depthDelta:(b.settings as any).searchDepth-(a.settings as any).searchDepth,openingLevelChanges:changes,flags};}
function isCompatible(a:ExperimentRecord,b:ExperimentRecord){const sa:any=a.settings,sb:any=b.settings;return a.mode===b.mode&&sa.greenAgent===sb.greenAgent&&sa.blueAgent===sb.blueAgent&&sa.greenDiversity===sb.greenDiversity&&sa.blueDiversity===sb.blueDiversity&&sa.maxPlies===sb.maxPlies&&sa.noProgressPlyLimit===sb.noProgressPlyLimit&&JSON.stringify(sa.selectedGreenOpenings??[])===JSON.stringify(sb.selectedGreenOpenings??[])&&sa.blueResponseMode===sb.blueResponseMode&&sa.searchDepth!==sb.searchDepth;}
function proposalForFlag(exp:ExperimentRecord,analysisId:string,f:AnalysisFlag):FollowUpProposal{const proposed:any=structuredClone(exp.settings); if("searchDepth" in proposed) proposed.searchDepth = Math.max(1,(proposed.searchDepth??1)+1); if(f.affectedOpenings.length&&"selectedGreenOpenings" in proposed) proposed.selectedGreenOpenings=[...new Set([...f.affectedOpenings,...f.affectedOpenings.map(o=>mirrorMoveLabel(o)).filter(Boolean)])]; if("gamesPerMatchup" in proposed) proposed.gamesPerMatchup=Math.max(proposed.gamesPerMatchup??1,2); return {proposalId:`proposal-${f.flagId}`,analysisId,experimentId:exp.experimentId,sourceFlagId:f.flagId,title:`Follow up: ${f.title}`,rationale:f.recommendedAction,estimatedTotalGames:estimate(proposed),expectedRuntimeWarning:"Created as a normal persisted experiment and not auto-started; higher depth may be slower.",inheritedSettings:exp.settings,changedFields:{searchDepth:(proposed as any).searchDepth,selectedGreenOpenings:(proposed as any).selectedGreenOpenings,gamesPerMatchup:(proposed as any).gamesPerMatchup},proposedSettings:proposed,createdAt:f.createdAt};}
export function analysisExportFiles(analysis:ExperimentAnalysis,flags:AnalysisFlag[],proposals:FollowUpProposal[]):ExportFile[]{return[{name:"analysis_summary.json",mime:"application/json",content:JSON.stringify(analysis,null,2)},{name:"analysis_summary.md",mime:"text/markdown",content:analysisMarkdown(analysis,flags,proposals)},{name:"opening_analysis.csv",mime:"text/csv",content:toCsv(analysis.openingResults as any)},{name:"mirror_analysis.csv",mime:"text/csv",content:toCsv(analysis.mirrorResults as any)},{name:"blue_reply_analysis.csv",mime:"text/csv",content:toCsv(analysis.blueReplyResults as any)},{name:"flags.csv",mime:"text/csv",content:toCsv(flags as any)},{name:"follow_up_proposals.json",mime:"application/json",content:JSON.stringify(proposals,null,2)},{name:"representative_games.csv",mime:"text/csv",content:toCsv(analysis.replayWorthyGames)},{name:"analyzer_config.json",mime:"application/json",content:JSON.stringify({ANALYZER_VERSION,ANALYSIS_RULE_CONFIG},null,2)}];}
function analysisMarkdown(a:ExperimentAnalysis,flags:AnalysisFlag[],props:FollowUpProposal[]){return [`# Sanctuary Experiment Analysis`,"",`Analyzer: ${a.analyzerVersion}`,`Status: ${a.status}`,`Sample: ${a.gameCount} games across ${a.openingCount} openings`,"","## Major findings",...flags.slice(0,10).map(f=>`- ${f.priority}: ${f.title} (${f.confidenceLevel} confidence) — ${f.explanation}`),"","## Recommended next experiment",props[0]?.title??"No specific follow-up proposal was generated.","","## Known limitations","Flags are triage signals from deterministic simulations and selected settings. They are not proof that Sanctuary is solved, balanced, imbalanced, or exploitable.",].join("\n");}
function coordKey(label:string){return (label.match(/\b[A-M]\d{1,2}\b/gi)??[]).join("-");}
function settingsSummary(s:ExperimentSettings){return{mode:s.mode,greenAgent:(s as any).greenAgent,blueAgent:(s as any).blueAgent,searchDepth:(s as any).searchDepth,maxPlies:(s as any).maxPlies,blueResponseMode:(s as any).blueResponseMode,openings:(s as any).selectedGreenOpenings?.length};}
function confidence(n:number,mirror=false):ConfidenceLevel{return n>=40&&mirror?"high":n>=20?"moderate":n>=10?"low":"very low";} function pct(n:number){return `${(n*100).toFixed(1)}%`;} function round(n:number){return Number((Number.isFinite(n)?n:0).toFixed(4));}
function group<T>(rows:T[],key:(x:T)=>string){const m=new Map<string,T[]>();for(const r of rows){const k=key(r);m.set(k,[...(m.get(k)??[]),r]);}return m;} function counts(xs:string[]){return xs.reduce((m:any,x)=>(m[x]=(m[x]??0)+1,m),{});} function maxCount<T>(m:Map<string,T[]>){return Math.max(0,...[...m.values()].map(v=>v.length));}
function sumMetrics(rows:CompletedGameRecord[]){const out:Record<string,number>={};for(const g of rows)for(const [k,v]of Object.entries(g.metrics??{}))if(typeof v==="number")out[k]=(out[k]??0)+v;return out;} function dist(a:Record<string,number>,b:Record<string,number>){const keys=new Set([...Object.keys(a),...Object.keys(b)]);const ta=Object.values(a).reduce((x,y)=>x+y,0)||1,tb=Object.values(b).reduce((x,y)=>x+y,0)||1;let d=0;for(const k of keys)d+=Math.abs((a[k]??0)/ta-(b[k]??0)/tb);return round(d/2);} function drawKind(g:CompletedGameRecord,k:string){return k==="repetitionDraws"?g.repetitionDiagnostics?.repetitionDraw:k==="noProgressDraws"?g.repetitionDiagnostics?.noProgressDraw:g.drawReason==="max-plies"||g.drawReason==="maxPlies";} function highest(flags:AnalysisFlag[]):FlagPriority{for(const p of ["high priority","suspicious","watch"] as const)if(flags.some(f=>f.priority===p))return p;return"normal";} function estimate(s:any){return s.mode==="targeted"?(s.selectedGreenOpenings?.length||1)*(s.gamesPerMatchup||1):s.mode==="opening"?13*(s.gamesPerOpening||1):s.games||1;} function replayWorthy(games:CompletedGameRecord[]){const out:Array<{gameId:string;reason:string}>=[];const sorted=[...games].sort((a,b)=>a.plies-b.plies); if(sorted[0])out.push({gameId:sorted[0].gameId,reason:"shortest game"}); const last=sorted[sorted.length-1]; if(last)out.push({gameId:last.gameId,reason:"longest game"}); for(const g of games){if(g.repetitionDiagnostics?.repetitionDraw)out.push({gameId:g.gameId,reason:"repetition draw"}); if(g.repetitionDiagnostics?.noProgressDraw)out.push({gameId:g.gameId,reason:"no-progress draw"}); if(g.drawReason==="max-plies"||g.drawReason==="maxPlies")out.push({gameId:g.gameId,reason:"max-plies draw"}); if(g.extractionFailure)out.push({gameId:g.gameId,reason:"extraction failure"}); if(g.carrierRouted)out.push({gameId:g.gameId,reason:"carrier routing"});}return out.slice(0,25);}
